GH-44432: [Swift] Use flatbuffers v24.3.7 (#44433)
### Rationale for this change

flatbuffers v24.3.7 includes https://github.com/google/flatbuffers/pull/8134 .

The current master has a build error:

https://github.com/apache/arrow/actions/runs/11357784776/job/31591213976?pr=44431#step:5:1114

```text
[51/77] Compiling Arrow ArrowType.swift
/arrow/swift/Arrow/Sources/Arrow/File_generated.swift:107:206: error: value of type 'Table' has no member 'postion'
  public var schema: org_apache_arrow_flatbuf_Schema? { let o = _accessor.offset(VTOFFSET.schema.v); return o == 0 ? nil : org_apache_arrow_flatbuf_Schema(_accessor.bb, o: _accessor.indirect(o + _accessor.postion)) }
                                                                                                                                                                                                   ~~~~~~~~~ ^~~~~~~
```

### What changes are included in this PR?

Use v24.3.7 instead of master.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* GitHub Issue: #44432

Authored-by: Sutou Kouhei <kou@clear-code.com>
Signed-off-by: Sutou Kouhei <kou@clear-code.com>