ARROW-8617: [Rust] Avoid loading simd_load_set_invalid which doesn't exist on aarch64
    error[E0432]: unresolved import `crate::compute::util::simd_load_set_invalid`
    --> /home/tyler/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/a446bce/rust/arrow/src/compute/kernels/arithmetic.rs:42:5
    |
    42 | use crate::compute::util::simd_load_set_invalid;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `simd_load_set_invalid` in `compute::util`

    Compiling thiserror v1.0.16
    error: aborting due to previous error

Closes #7049 from rtyler/aarch64-fixes

Authored-by: R. Tyler Croy <rtyler@brokenco.de>
Signed-off-by: Paddy Horan <paddyhoran@hotmail.com>